language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew assemble testCoverage"
after_success:
- tools/release/deploy_snapshot.sh
- bash <(curl -s https://codecov.io/bash)
before_install:
- yes | sdkmanager "platforms;android-29"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: S9QNLPdjmGGYM8KChCjcmWOodzcFTzIQ6oPZB88bbnGzp++Zxss3tgGE+KqMSynu2RxSAqU18BXbCXKXYuSO0DmZmlVIQBxFv1XDGpoSbGTqhVI6g0ewiS2mhX6tJxOkUARdbX0C9EEH5bhlGjcjSJ82oPE+z4RPu21INh52ue0gk4S5Z+dif+VxG/qFh4OYdDmIFn1kVg2xaukgV5B+75++DYPFmX7+gkK/X95jQ5mcmahu8thpvS5Hynxiu/XAQ+JedC38Vx38GmcVoaQ5Rw8j3Iwsfqlo4Ob7G8VM/jw4vutcs6E4rlU6rTGSWd7BHukhl04aBg8jmj3YQtQl66VkHCwiSi0E6quTxK7fUjsrBFrSBz3PNZAZNTgZDRtJRyIA1zkkqjTMqdpxrsAiU7Zv9PIjXE1YWhjm+1TYAmAxU3h3yUYHOBbbklbsHsaSoMFY02UmwTx2GtSslECcAAXTS9m0sbe1XMxKeyD4DgpORVG+LSSYbkFcniB9IRui1uaaWquIAPhqTA3nRfbAHix/kCa+iGLb1P35SrVXDIWIalnKWeZYRlwrjLhf45c+fh+hfsjJXCmKN4Vsq+wu6+0mjKk6aImgGpN+j/xPau8i4YJgdA1ULHirjf7D82M1bCE5oMsopEv1VNCXrUI/2YC2kIKntpdKXhOeszCY490=
  - secure: MQ44uyB8FOUS6pAYliw+JTqDBvH1jNdOF6oehUiadPXvuaQY+6xqUlygrCegsyuOL3OS43VB+LyxaNmuFLd2NKH+BPSSuuV3nHp1wUxsUeLKqlx+pNqXX6eNwePv59/iOlsv1TPveUAsSqxwtGzqzxMtdRbi2ttm1faYdgmubjSuQVXF6+e/y1a7+YkEPo31jhqmSdTBzv16gEu8zTZBlKMSmSXwJoPGsnGZxUs+RVf3mbrYk9QGr4L8idlv6221umERZhUI+4okctJolakyFBbthQdeLfcY/Gs4xC+VGWYkkXwJccBFAWZg9AYQz3qjVY657TNjMSfX6xMUzuxAS6fuG64YD7yW1Uds2f81mE4BW4BZyNIB9LLnRuTGqPNgOl2EFEawK/OpSNlyrvvFW5L1MI7L9uJr+eUowCzgNGuxcndRlYqn17xS1YpUrVT/CDhcE+d5v+ERFzMLRxClGjO9IigXTyYC25KlQOBTah9Q93m+PdBXJToyESONst4fCRCFhctXzrUEV3wMNYyX3TK/zqLHu6IW4CWwk6yoj/CKvu/QiNpUTB/jBICfHWRw4KofQw50XkWZlBv/DXVDi73en56azPiPG3FwvnudyE79UDVKqUCf8IyIHwPl8ok5g2ttJAwoJwDOpfmrL3WQzEauc7Th8b4E74DnzU86bFo=
  - secure: lyUIbhAk3C2CeGaukd95w3weoIKZDXhYv6vhTobSnLnpPfZEWqf73VXHYmurp27BICl5X0CoR8vJWV0L3z+wuWTPk2ECUWA+jNiDXB8atphZO/l5PW066j9OCbRpoq2B6HVRa6RGR70hCZvXe1LjLsZsiaIYTFEXhidGdaWLOosar1VRk/eoREcv5svtC5qYBfUYTC761ld30p8DjhkWpU2XV79MwDcKPHvHlPEerkP9++4fT8PZjQyqZPgou2dyVlBn9HvrSAKNABKe4ov352NXrYxmhf/4BKBH++j4DS5h4wmPz+eAl4zq/b0bjIIDr1sdPmaWPoJxuNHFKkgzmMx6DKleXy9bBqEAjmGGeo0xcJ0/G8KW/jRjVqdS5hVQG+StPRLwtzOlJqbfoxjRDg+pjBpzY5n/PBjbHcGVX+ZjljXgpWmjTRsrQYXECAw7W6lw8clqLKVw1LM0eMiq+6Wd5V3JFTC+PiY5Ylzsu1FwhYI3U5kkVwLFWrsd1ZX1uypFGfBOic/f5mElVvTAj5Cu/b99zxkAIvpLTFV2WPoTsfYLpI7VyqrU1J9wxXksXYs6P+0uHrqsg4IO35HlbnS2RcAJJlcMx4v9DeEdbhOy/gcnIsO1JNTuq9MyYfAxbUajOpF56T5wu196qHQrxMZFpxG7TyfVOI4VLOnJdxY=
  - secure: q4ZzG/vBLRUz/d8GPxF2GUaIy6JetwkK2wUXfhWZGY6WVcYFcG8e2Jiw9dXYDHuI9uManelHnPQ2BHX9vopnwzET2QKAAvpc2iNqz/pBtns56n/BO5l9qrljDhxeQwoNZVwucavOE7BdJjLOz91wJRZg7vOkjP2cvupdfjscv9kiHJsXGl4boN1mVyD5tEu8hiaqvRVZDz7UJgOaLUE2THYRIWHje4JGCh2XtRDwGNOlvC7GuML2tkVdu23jM320CkcawF05RzWXyCz9XePzrT870WjVk/L9f2/yudPQ4FXC3RkhnfAZ2kfEU8DMD45sY6JKMFGV1jGFdnIetBsBwPKy9khDDlr9yS4YD6HtSvsvCsiaikDOG2Y0m621DEzKFlHckBOGV+ASD2iT0B0NV6avKcStvkliYTXIdR6LErhctIuE+mMm0n0BSrR0+cBScBF//YjrFfwGpympLwC3WYxKUrIBulQlLii6J5nHgj9tT6s0VBXZ+H0BsRoBCayc4U4bQRY33CsKahmjGt7uBloVVPMPaj/D/msuZZUWHoW8ShIV2A2xImb3BmnEUx4UhvSM5WAn8z83zn8eoanNxQNcUW+Wk0q+4o8wOoCODLT1b0w1eDx8bdJy9Lvuz+ayzB9j+zxArBFbrpYq1RgvFT3UJSnt0Ab+4/0TfLck4+I=
  - secure: CEp3bCgWTu2qDnXTX+eDZmt329UCvlcLWg7cSsljMAlvMg26vhCNdwQtlInjaKr65X4TlaQf4NpEZfl2lphKvWqS5g+C7MD/JPX85LYmU3uCZiorDVm/se3Dc4agEva7IxYOYq0e+eFNWEh8F6EQdVPZYy3+6sTSACMQ0M79WBkPWInZGmJwqtPu46CJCuJX65qZbUIf3QIV626qmhysw1KDTZ0ModR5zMeDRA9xosPA+nG+/Fduw/SoSvHb+Z0u85D4cFqLWShfdA8aJCikxGgucwmqYlVGECRgIks8WklP3iWDsXdQIggmajf21MulZIv5EIj9HDh/O/vyUVq9gWiousQsaqaMC6IXmBUl/aU56XApa+LYPwFvzRKOQCu1ihl7q8Ffc/w+6dKkNb4yXvQL3uKVifzFmXc2lRv6koeCkqtryaAGiSd76S+QnOxSLReykFsmRNQe3WoW47ngJC+r5+1sNAjoUKw9bjVjd1YFvxaPLLrGrSB+b1wMgKygEdR/6Wktmc+O9T4XyrXklDZbSKXJdxUWgUqaswFcOt6ZU1zcosKM2Ab2jytlJeEQmRugLv1Nn443DWutEz37GfpkEBSWOBJ7IvilXFF2aBrE9RGQQzYbX2mMv7wwFJMDqiwIsS6amGn937S23qcgIeYL0gEra71IjpIYBm7QZmc=
